org.gradle.jvmargs=-Xmx4G -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
org.gradle.daemon=false
org.gradle.internal.filelock.lockListenerPort=49700
org.gradle.internal.filelock.lockListenerAddress=127.0.0.1
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.newDsl=false
